---
bibliography: "Learning Technology-E17 Flashnote.bib"
# csl: "modern-language-association.csl"
# csl: "apa.csl"
# csl: "chicago-author-date.csl"
papersize: a4
geometry: margin=3.5cm
toc: True
indent: True

codeBlockCaptions: True
autoSectionLabels: False
toc-depth: 2
header-includes: |
  \usepackage{pdfpages}
  
  \usepackage{tcolorbox}
  
  \providecommand{\subtitle}[1]{%
  \usepackage{titling}
  \posttitle{%
    \par\large#1\end{center}}
  }
  
  \providecommand{\institute}[1]{%
    \postauthor{\end{tabular}\par\leavemode\newline\textit{#1}\end{center}}
  }
---